---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
- name: resource-carts

run:
 dir: resource-carts
 path: nvm
 args:
 - -DskipTests
 - package
