---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
- name: resource-carts

outputs:
- name: docker-build

run:
 path: bash
 args:
 - -exc
 - |
    export DOCKER_BUILD_DIR=$PWD/docker-build
    (cd resource-carts && mvn -DskipTests package  && cp -r target Dockerfile $DOCKER_BUILD_DIR)