---
resources:
- name: resource-carts
  type: git
  source:
    uri: https://github.com/saraim82/carts.git
    branch: master

jobs:
- name: job-build
  public: true
  plan:
  - get: resource-carts
    trigger: true
  - task: run build
    file: resource-carts/ci/tasks/run_build.yml


- name: job-test
  public: true
  plan:
  - get: resource-carts
    passed: [job-build]
  - task: run test
    file: resource-carts/ci/tasks/run_test.yml