---
resources:
- name: resource-carts
  type: git
  source:
    uri: https://github.com/saraim82/carts.git
    branch: master

jobs:
- name: job-build
  public: true
  plan:
  - get: resource-carts
  - task: run build
    file: resource-carts/ci/tasks/run_build.yml


#- name: job-test
#  public: true
#  plan:
#  - get: resource-carts
#  - get: resource-git
#  - task: test
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source: {repository: ubuntu, tag: latest}
#      inputs:
#      - name: resource-carts
#      - name: resource-git
#      run:
#        path:  resource-git/./scripts/run_test.sh